// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.28.2
// source: service.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RaftNodeClient is the client API for RaftNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftNodeClient interface {
	RequestVote(ctx context.Context, in *RPCBallot, opts ...grpc.CallOption) (*RPCBallotResponse, error)
	AppendEntries(ctx context.Context, in *RPCAppendEntriesRequest, opts ...grpc.CallOption) (*RPCAppendEntriesResponse, error)
	JoinCluster(ctx context.Context, in *RPCJoinClusterRequest, opts ...grpc.CallOption) (*RPCJoinClusterResponse, error)
}

type raftNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftNodeClient(cc grpc.ClientConnInterface) RaftNodeClient {
	return &raftNodeClient{cc}
}

func (c *raftNodeClient) RequestVote(ctx context.Context, in *RPCBallot, opts ...grpc.CallOption) (*RPCBallotResponse, error) {
	out := new(RPCBallotResponse)
	err := c.cc.Invoke(ctx, "/RaftNode/RequestVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftNodeClient) AppendEntries(ctx context.Context, in *RPCAppendEntriesRequest, opts ...grpc.CallOption) (*RPCAppendEntriesResponse, error) {
	out := new(RPCAppendEntriesResponse)
	err := c.cc.Invoke(ctx, "/RaftNode/AppendEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftNodeClient) JoinCluster(ctx context.Context, in *RPCJoinClusterRequest, opts ...grpc.CallOption) (*RPCJoinClusterResponse, error) {
	out := new(RPCJoinClusterResponse)
	err := c.cc.Invoke(ctx, "/RaftNode/JoinCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftNodeServer is the server API for RaftNode service.
// All implementations must embed UnimplementedRaftNodeServer
// for forward compatibility
type RaftNodeServer interface {
	RequestVote(context.Context, *RPCBallot) (*RPCBallotResponse, error)
	AppendEntries(context.Context, *RPCAppendEntriesRequest) (*RPCAppendEntriesResponse, error)
	JoinCluster(context.Context, *RPCJoinClusterRequest) (*RPCJoinClusterResponse, error)
	mustEmbedUnimplementedRaftNodeServer()
}

// UnimplementedRaftNodeServer must be embedded to have forward compatible implementations.
type UnimplementedRaftNodeServer struct {
}

func (UnimplementedRaftNodeServer) RequestVote(context.Context, *RPCBallot) (*RPCBallotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVote not implemented")
}
func (UnimplementedRaftNodeServer) AppendEntries(context.Context, *RPCAppendEntriesRequest) (*RPCAppendEntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendEntries not implemented")
}
func (UnimplementedRaftNodeServer) JoinCluster(context.Context, *RPCJoinClusterRequest) (*RPCJoinClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinCluster not implemented")
}
func (UnimplementedRaftNodeServer) mustEmbedUnimplementedRaftNodeServer() {}

// UnsafeRaftNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftNodeServer will
// result in compilation errors.
type UnsafeRaftNodeServer interface {
	mustEmbedUnimplementedRaftNodeServer()
}

func RegisterRaftNodeServer(s grpc.ServiceRegistrar, srv RaftNodeServer) {
	s.RegisterService(&RaftNode_ServiceDesc, srv)
}

func _RaftNode_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCBallot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftNodeServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RaftNode/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftNodeServer).RequestVote(ctx, req.(*RPCBallot))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftNode_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCAppendEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftNodeServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RaftNode/AppendEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftNodeServer).AppendEntries(ctx, req.(*RPCAppendEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftNode_JoinCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCJoinClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftNodeServer).JoinCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RaftNode/JoinCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftNodeServer).JoinCluster(ctx, req.(*RPCJoinClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RaftNode_ServiceDesc is the grpc.ServiceDesc for RaftNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RaftNode",
	HandlerType: (*RaftNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestVote",
			Handler:    _RaftNode_RequestVote_Handler,
		},
		{
			MethodName: "AppendEntries",
			Handler:    _RaftNode_AppendEntries_Handler,
		},
		{
			MethodName: "JoinCluster",
			Handler:    _RaftNode_JoinCluster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

// RaftClientServiceClient is the client API for RaftClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftClientServiceClient interface {
	AddClient(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClusterInfo, error)
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
}

type raftClientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftClientServiceClient(cc grpc.ClientConnInterface) RaftClientServiceClient {
	return &raftClientServiceClient{cc}
}

func (c *raftClientServiceClient) AddClient(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClusterInfo, error) {
	out := new(ClusterInfo)
	err := c.cc.Invoke(ctx, "/RaftClientService/AddClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClientServiceClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, "/RaftClientService/Write", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftClientServiceServer is the server API for RaftClientService service.
// All implementations must embed UnimplementedRaftClientServiceServer
// for forward compatibility
type RaftClientServiceServer interface {
	AddClient(context.Context, *emptypb.Empty) (*ClusterInfo, error)
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	mustEmbedUnimplementedRaftClientServiceServer()
}

// UnimplementedRaftClientServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRaftClientServiceServer struct {
}

func (UnimplementedRaftClientServiceServer) AddClient(context.Context, *emptypb.Empty) (*ClusterInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddClient not implemented")
}
func (UnimplementedRaftClientServiceServer) Write(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedRaftClientServiceServer) mustEmbedUnimplementedRaftClientServiceServer() {}

// UnsafeRaftClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftClientServiceServer will
// result in compilation errors.
type UnsafeRaftClientServiceServer interface {
	mustEmbedUnimplementedRaftClientServiceServer()
}

func RegisterRaftClientServiceServer(s grpc.ServiceRegistrar, srv RaftClientServiceServer) {
	s.RegisterService(&RaftClientService_ServiceDesc, srv)
}

func _RaftClientService_AddClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftClientServiceServer).AddClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RaftClientService/AddClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftClientServiceServer).AddClient(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftClientService_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftClientServiceServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RaftClientService/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftClientServiceServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RaftClientService_ServiceDesc is the grpc.ServiceDesc for RaftClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RaftClientService",
	HandlerType: (*RaftClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddClient",
			Handler:    _RaftClientService_AddClient_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _RaftClientService_Write_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
